/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppVisitsRouteImport } from './routes/_app.visits'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMyCallsRouteImport } from './routes/_app.my-calls'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const AppRoute = AppRouteImport.update({ id: '/_app', getParentRoute: () => rootRouteImport } as any)
const AppDashboardRoute = AppDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AppRoute } as any)
const AppStudentsRoute = AppStudentsRouteImport.update({ id: '/students', path: '/students', getParentRoute: () => AppRoute } as any)
const AppStaffRoute = AppStaffRouteImport.update({ id: '/staff', path: '/staff', getParentRoute: () => AppRoute } as any)
const AppActivityRoute = AppActivityRouteImport.update({ id: '/activity', path: '/activity', getParentRoute: () => AppRoute } as any)
const AppVisitsRoute = AppVisitsRouteImport.update({ id: '/visits', path: '/visits', getParentRoute: () => AppRoute } as any)
const AppReportsRoute = AppReportsRouteImport.update({ id: '/reports', path: '/reports', getParentRoute: () => AppRoute } as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({ id: '/notifications', path: '/notifications', getParentRoute: () => AppRoute } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AppRoute } as any)
const AppMyCallsRoute = AppMyCallsRouteImport.update({ id: '/my-calls', path: '/my-calls', getParentRoute: () => AppRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '': typeof AppRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/students': typeof AppStudentsRoute
  '/staff': typeof AppStaffRoute
  '/activity': typeof AppActivityRoute
  '/visits': typeof AppVisitsRoute
  '/reports': typeof AppReportsRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/my-calls': typeof AppMyCallsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '': typeof AppRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/students': typeof AppStudentsRoute
  '/staff': typeof AppStaffRoute
  '/activity': typeof AppActivityRoute
  '/visits': typeof AppVisitsRoute
  '/reports': typeof AppReportsRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/my-calls': typeof AppMyCallsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/visits': typeof AppVisitsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/my-calls': typeof AppMyCallsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '' | '/dashboard' | '/students' | '/staff' | '/activity' | '/visits' | '/reports' | '/notifications' | '/settings' | '/my-calls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '' | '/dashboard' | '/students' | '/staff' | '/activity' | '/visits' | '/reports' | '/notifications' | '/settings' | '/my-calls'
  id: '__root__' | '/' | '/auth' | '/_app' | '/_app/dashboard' | '/_app/students' | '/_app/staff' | '/_app/activity' | '/_app/visits' | '/_app/reports' | '/_app/notifications' | '/_app/settings' | '/_app/my-calls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_app': { id: '/_app'; path: ''; fullPath: ''; preLoaderRoute: typeof AppRouteImport; parentRoute: typeof rootRouteImport }
    '/_app/dashboard': { id: '/_app/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AppDashboardRouteImport; parentRoute: typeof AppRoute }
    '/_app/students': { id: '/_app/students'; path: '/students'; fullPath: '/students'; preLoaderRoute: typeof AppStudentsRouteImport; parentRoute: typeof AppRoute }
    '/_app/staff': { id: '/_app/staff'; path: '/staff'; fullPath: '/staff'; preLoaderRoute: typeof AppStaffRouteImport; parentRoute: typeof AppRoute }
    '/_app/activity': { id: '/_app/activity'; path: '/activity'; fullPath: '/activity'; preLoaderRoute: typeof AppActivityRouteImport; parentRoute: typeof AppRoute }
    '/_app/visits': { id: '/_app/visits'; path: '/visits'; fullPath: '/visits'; preLoaderRoute: typeof AppVisitsRouteImport; parentRoute: typeof AppRoute }
    '/_app/reports': { id: '/_app/reports'; path: '/reports'; fullPath: '/reports'; preLoaderRoute: typeof AppReportsRouteImport; parentRoute: typeof AppRoute }
    '/_app/notifications': { id: '/_app/notifications'; path: '/notifications'; fullPath: '/notifications'; preLoaderRoute: typeof AppNotificationsRouteImport; parentRoute: typeof AppRoute }
    '/_app/settings': { id: '/_app/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AppSettingsRouteImport; parentRoute: typeof AppRoute }
    '/_app/my-calls': { id: '/_app/my-calls'; path: '/my-calls'; fullPath: '/my-calls'; preLoaderRoute: typeof AppMyCallsRouteImport; parentRoute: typeof AppRoute }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppActivityRoute: typeof AppActivityRoute
  AppVisitsRoute: typeof AppVisitsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppMyCallsRoute: typeof AppMyCallsRoute
}
const appRouteChildren: AppRouteChildren = {
  AppDashboardRoute,
  AppStudentsRoute,
  AppStaffRoute,
  AppActivityRoute,
  AppVisitsRoute,
  AppReportsRoute,
  AppNotificationsRoute,
  AppSettingsRoute,
  AppMyCallsRoute,
}
const AppRouteWithChildren = AppRoute._addFileChildren(appRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
